name: kraken-hello-world-hollowsaibot # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  kraken-hello-world-hollowsaibot:
    command: MakeFile.sh

parts:
  my-service:
    plugin: dump
    source: out/
  kraken-hello-world-hollowsaibot:
    # See 'snapcraft plugins'
    plugin: autotools
    source: .
    override-build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    build-packages:
      - openjdk-8-jdk
      - openjdk-8-jre
  # It will copy wallpaperdownloader script into /bin/
  # This script contains all the commands needed (sets env variables, launches the jar file...) to
  # execute the application
  wrapper:
    plugin: dump
    source: .
    organize:
      /MakeFile.sh: bin/MakeFile.sh