name: kraken
version: '1.0.0'
summary: Application for Mind Mapping, Knowledge and Project Management
description: |
  Kraken is a free and open source software application that supports
  thinking, sharing information and getting things done at work, in school
  and at home. The core of the software is tools for mind mapping (also
  known as concept mapping or information mapping) and using mapped
  information.